# Generated by Django 6.0 on 2025-12-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='meal_type',
        ),
    ]
