# Generated by Django 6.0 on 2025-12-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_api', '0002_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='meal_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], default='Veg', max_length=10),
        ),
    ]
