# Generated by Django 6.0.1 on 2026-01-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_api', '0003_attendance_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='fixed_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='bill',
            name='non_veg_daily_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='bill',
            name='veg_daily_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
