# Generated by Django 6.0.1 on 2026-01-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_api', '0004_bill_fixed_charges_bill_non_veg_daily_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='non_veg_daily_rate',
            new_name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='fixed_charges',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='veg_daily_rate',
        ),
        migrations.AddField(
            model_name='bill',
            name='electricity_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='bill',
            name='establishment_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='bill',
            name='nv_plate_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='bill',
            name='room_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='bill',
            name='water_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
