# Generated by Django 6.0.1 on 2026-01-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_api', '0005_rename_non_veg_daily_rate_bill_daily_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='non_veg_plate_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='veg_plate_count',
            field=models.IntegerField(default=0),
        ),
    ]
