# Generated by Django 6.0.1 on 2026-01-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess_api', '0006_attendance_non_veg_plate_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='non_veg_plate_count',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='veg_plate_count',
        ),
    ]
